version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: todo
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_pass
    ports:
      - "54321:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: "5432"
      DB_USER: db_user
      DB_PASSWORD: db_pass
      DB_NAME: todo
    depends_on:
      - db
    labels:
      - "version.go=1.24"

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data: